# Generated by Django 2.0 on 2017-12-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20171228_0643'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactPerson',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_person_email_address',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_person_first_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_person_last_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_person_mobile',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_person_salutation',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_person_work_phone',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
