# Generated by Django 2.0 on 2017-12-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20171228_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_display_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='currency',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
