# Generated by Django 2.0 on 2017-12-28 07:47

from django.db import migrations, models
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20171228_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contact',
            name='billing_address_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='shipping_address_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
