# Generated by Django 2.0 on 2017-12-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20171228_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='currency',
            field=models.CharField(blank=True, choices=[('AFN', 'AFN-Afghani'), ('AUD', 'AUD-Austrilian Dollar'), ('CAD', 'CAD-Canadian Dollar'), ('CNY', 'CNY-Yuan Renminbi'), ('EUR', 'EUR-Euro'), ('GBP', 'GBP-Pound Sterling'), ('INR', 'INR-Indian Rupee'), ('JPY', 'JPY-Yen'), ('USD', 'USD-US Dollar'), ('ZAR', 'ZAR-Rand')], max_length=10, null=True),
        ),
    ]
