# Generated by Django 2.0 on 2017-12-28 08:02

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_auto_20171228_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='billing_address_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_person_work_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='shipping_address_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='work_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=40, null=True),
        ),
    ]
