# Generated by Django 2.0 on 2017-12-28 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_auto_20171228_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_address_attention', models.CharField(blank=True, max_length=40, null=True)),
                ('billing_address_street_1', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_address_street_2', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_address_city', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_address_state', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_address_zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('billing_address_country', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_address_phone', models.CharField(blank=True, max_length=40, null=True)),
                ('billing_address_fax', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(blank=True, max_length=4, null=True)),
                ('first_name', models.CharField(blank=True, max_length=40, null=True)),
                ('last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('email_address', models.EmailField(max_length=255, unique=True)),
                ('work_phone', models.CharField(blank=True, max_length=40, null=True)),
                ('mobile', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skype_account', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=40, null=True)),
                ('portal', models.BooleanField(default=False)),
                ('portal_language', models.CharField(blank=True, max_length=40, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address_attention', models.CharField(blank=True, max_length=40, null=True)),
                ('shipping_address_street_1', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_address_street_2', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_address_city', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_address_state', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_address_zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('shipping_address_country', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_address_phone', models.CharField(blank=True, max_length=40, null=True)),
                ('shipping_address_fax', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='billing_address_attention',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='billing_address_city',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='billing_address_country',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='billing_address_fax',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='billing_address_phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='billing_address_state',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='billing_address_street_1',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='billing_address_street_2',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='billing_address_zip_code',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_person_email_address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_person_first_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_person_last_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_person_mobile',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_person_salutation',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_person_work_phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='department',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='portal',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='portal_language',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='shipping_address_attention',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='shipping_address_city',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='shipping_address_country',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='shipping_address_fax',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='shipping_address_phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='shipping_address_state',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='shipping_address_street_1',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='shipping_address_street_2',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='shipping_address_zip_code',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='skype_account',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='twitter',
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='salutation',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.BillingAddress'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.ContactPerson'),
        ),
        migrations.AddField(
            model_name='contact',
            name='other_detail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.OtherDetail'),
        ),
        migrations.AddField(
            model_name='contact',
            name='remarks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Remark'),
        ),
        migrations.AddField(
            model_name='contact',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.ShippingAddress'),
        ),
    ]
