# Generated by Django 2.0 on 2017-12-28 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_contact_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
