# Generated by Django 2.0 on 2017-12-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0019_auto_20171228_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='billing_address_fax',
            new_name='attention',
        ),
        migrations.RenameField(
            model_name='billingaddress',
            old_name='billing_address_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='billingaddress',
            old_name='billing_address_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='billingaddress',
            old_name='billing_address_attention',
            new_name='fax',
        ),
        migrations.RenameField(
            model_name='billingaddress',
            old_name='billing_address_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='billingaddress',
            old_name='billing_address_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='billingaddress',
            old_name='billing_address_street_1',
            new_name='street_1',
        ),
        migrations.RenameField(
            model_name='billingaddress',
            old_name='billing_address_street_2',
            new_name='street_2',
        ),
        migrations.RenameField(
            model_name='billingaddress',
            old_name='billing_address_zip_code',
            new_name='zip_code',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_address_attention',
            new_name='attention',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_address_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_address_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_address_fax',
            new_name='fax',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_address_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_address_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_address_street_1',
            new_name='street_1',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_address_street_2',
            new_name='street_2',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_address_zip_code',
            new_name='zip_code',
        ),
        migrations.AlterField(
            model_name='contact',
            name='remarks',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Remark',
        ),
    ]
