# Generated by Django 2.0 on 2017-12-28 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0022_auto_20171228_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='additional_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.AdditionalAddress'),
        ),
    ]
