# Generated by Django 2.0 on 2017-12-29 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0025_auto_20171229_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactperson',
            name='email_address',
        ),
    ]
