# Generated by Django 2.0 on 2017-12-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0026_remove_contactperson_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactperson',
            name='email_address',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_address',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
    ]
