# Generated by Django 2.0 on 2017-12-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0027_auto_20171229_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email_address',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='email_address',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
