# Generated by Django 2.0 on 2017-12-31 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0028_auto_20171231_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='additional_address',
        ),
        migrations.DeleteModel(
            name='AdditionalAddress',
        ),
    ]
