# Generated by Django 2.0 on 2018-01-02 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0029_auto_20171231_0840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='attention',
            new_name='b_attention',
        ),
        migrations.RenameField(
            model_name='billingaddress',
            old_name='city',
            new_name='b_city',
        ),
        migrations.RenameField(
            model_name='billingaddress',
            old_name='country',
            new_name='b_country',
        ),
        migrations.RenameField(
            model_name='billingaddress',
            old_name='fax',
            new_name='b_fax',
        ),
        migrations.RenameField(
            model_name='billingaddress',
            old_name='phone',
            new_name='b_phone',
        ),
        migrations.RenameField(
            model_name='billingaddress',
            old_name='state',
            new_name='b_state',
        ),
        migrations.RenameField(
            model_name='billingaddress',
            old_name='street_1',
            new_name='b_street_1',
        ),
        migrations.RenameField(
            model_name='billingaddress',
            old_name='street_2',
            new_name='b_street_2',
        ),
        migrations.RenameField(
            model_name='billingaddress',
            old_name='zip_code',
            new_name='b_zip_code',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='attention',
            new_name='s_attention',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='s_city',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='country',
            new_name='s_country',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='fax',
            new_name='s_fax',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='phone',
            new_name='s_phone',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='s_state',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='street_1',
            new_name='s_street_1',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='street_2',
            new_name='s_street_2',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zip_code',
            new_name='s_zip_code',
        ),
    ]
