# Generated by Django 2.0 on 2018-01-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0031_auto_20180103_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_display_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='currency',
            field=models.CharField(choices=[('AFN', 'AFN-Afghani'), ('AUD', 'AUD-Austrilian Dollar'), ('CAD', 'CAD-Canadian Dollar'), ('CNY', 'CNY-Yuan Renminbi'), ('EUR', 'EUR-Euro'), ('GBP', 'GBP-Pound Sterling'), ('INR', 'INR-Indian Rupee'), ('JPY', 'JPY-Yen'), ('USD', 'USD-US Dollar'), ('ZAR', 'ZAR-Rand')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='work_phone',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='mobile',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='work_phone',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
