# Generated by Django 2.0 on 2018-01-03 09:30

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0037_auto_20180103_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaladdress',
            name='attention',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='additionaladdress',
            name='city',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='additionaladdress',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='additionaladdress',
            name='fax',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='additionaladdress',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='additionaladdress',
            name='state',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='additionaladdress',
            name='street_1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='additionaladdress',
            name='street_2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='additionaladdress',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='attention',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='city',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='fax',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='state',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='street_1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='street_2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_display_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='attention',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='fax',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='street_1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='street_2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
    ]
