# Generated by Django 2.0 on 2018-01-03 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0038_auto_20180103_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMoreField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skype_account', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('designation', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('department', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='department',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='skype_account',
        ),
        migrations.AlterField(
            model_name='contact',
            name='additional_address',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.AdditionalAddress'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='billing_address',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.BillingAddress'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_person',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.ContactPerson'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='remarks',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='shipping_address',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.ShippingAddress'),
        ),
        migrations.AddField(
            model_name='contact',
            name='add_more_fields',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.AddMoreField'),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='add_more_fields',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.AddMoreField'),
        ),
    ]
