# Generated by Django 2.0 on 2018-01-04 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0039_auto_20180103_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='add_more_fields',
            new_name='add_more_field',
        ),
        migrations.RenameField(
            model_name='contactperson',
            old_name='add_more_fields',
            new_name='add_more_field',
        ),
    ]
