# Generated by Django 2.0 on 2018-01-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0042_auto_20180104_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email_address',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='email_address',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
