# Generated by Django 2.0 on 2018-01-29 09:47

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=255, unique=True)),
                ('company', models.CharField(default='', max_length=255)),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to=users.utils.get_company_directory)),
                ('avatar', models.ImageField(blank=True, default='', null=True, upload_to=users.utils.get_user_directory)),
                ('country', models.CharField(default='Philippines', max_length=200)),
                ('province', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('street', models.CharField(default='', max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False, verbose_name='activate')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('name', 'company')},
        ),
    ]
