# Generated by Django 2.0 on 2018-02-02 03:42

from django.db import migrations, models
import django.db.models.deletion
import invoices.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.PositiveIntegerField()),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent')], default='draft', max_length=10)),
                ('paid', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, max_length=255, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to=invoices.utils.get_invoice_directory)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
    ]
