# Generated by Django 2.0 on 2018-01-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('hourly', 'Hourly')], max_length=10),
        ),
    ]
