# Generated by Django 2.0 on 2018-02-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20180223_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
