# Generated by Django 2.0 on 2018-01-25 03:03

from django.db import migrations, models
import invoices.utils


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20180123_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=invoices.utils.get_invoice_directory),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('hourly', 'Hourly')], default='fixed', max_length=10),
        ),
    ]
