# Generated by Django 2.0 on 2018-02-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20180223_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
