# Generated by Django 2.0 on 2018-01-26 07:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0003_auto_20180125_0303'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('invoice_number', 'owner'), ('order_number', 'owner')},
        ),
    ]
