# Generated by Django 2.0 on 2018-01-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_display_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email_address',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='skype_account',
            field=models.CharField(blank=True, default='', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='work_phone',
            field=models.CharField(blank=True, default='', max_length=18, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('work_phone', 'mobile'), ('first_name', 'last_name')},
        ),
    ]
