# Generated by Django 2.0 on 2018-02-05 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_company_owner'),
        ('clients', '0002_auto_20180202_0342'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('mobile', 'company'), ('email', 'company'), ('display_name', 'company')},
        ),
    ]
