# Generated by Django 2.0 on 2018-01-31 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('clients', '0002_auto_20180130_0807'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('display_name', 'company')},
        ),
    ]
