# Generated by Django 2.0 on 2018-01-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20180109_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_display_name',
            field=models.CharField(max_length=255),
        ),
    ]
