# Generated by Django 2.0 on 2018-01-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20180109_1318'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('work_phone', 'mobile')},
        ),
    ]
