# Generated by Django 2.0 on 2018-02-07 06:55

import clients.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_company_owner'),
        ('clients', '0003_auto_20180205_0713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='display_name',
            new_name='client_company',
        ),
        migrations.AddField(
            model_name='client',
            name='client_company_logo',
            field=models.ImageField(blank=True, null=True, upload_to=clients.utils.get_client_company_logo_dir),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('client_company', 'company'), ('mobile', 'company'), ('email', 'company')},
        ),
    ]
