# Generated by Django 2.0 on 2018-02-08 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='middle_name',
        ),
    ]
