# Generated by Django 2.0 on 2018-01-23 03:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0006_auto_20180123_0145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temp',
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('display_name', 'owner'), ('email', 'owner'), ('mobile', 'owner')},
        ),
    ]
