# Generated by Django 2.0 on 2018-02-08 05:13

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_client_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True),
        ),
    ]
