# Generated by Django 2.0 on 2018-01-26 09:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0007_auto_20180123_0313'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('email', 'owner'), ('display_name', 'owner')},
        ),
    ]
