# Generated by Django 2.0 on 2018-01-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_auto_20180109_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
