# Generated by Django 2.0 on 2018-02-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20180202_0454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='hours',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('quality', 'Quality')], default='fixed', max_length=10),
        ),
    ]
